# -- 主题参数 --
# 完整参考：https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # light 或 dark
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = false

replyByEmail = false

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

defaultBackgroundImage = "images/site-background.svg"
backgroundCanvas = true
hotlinkFeatureImage = false

fingerprintAlgorithm = "sha512"

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

[languageRedirect]
  enabled = false
  storageKey = "blowfish_preferred_language"
  browserRedirectHomeOnly = true
  storedLanguageRedirect = true

[header]
  layout = "basic" # basic / fixed / fixed-fill / fixed-gradient / fixed-fill-blur / floating

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # page / profile / hero / card / background / landing / custom
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false
  disableHeroImageFilter = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/euinharry/my-blog/edit/main/content/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showReadingProgress = false
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showCategories = true
  showTags = true
  showCategoriesInSecondaryColor = false
  showAuthorsBadges = false
  showWordCount = true
  showZenMode = false

[list]
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[seo]

[firebase]
[fathomAnalytics]
[umamiAnalytics]
[selineAnalytics]
[buymeacoffee]
[verification]
[rssnext]
[advertisement]